export const BannerList = [
  {
    id: 1,
    name: "Everything Everywhere All at Once",
    backdrop: "images/banner/everything-everywhere.jpg",
    link: "/movie/12051",
    trailer: "https://youtu.be/wxN1T1uxQ2g",
    tagline: "The universe is so much bigger than you realize.",
  },
  {
    id: 2,
    name: "John Wick: Chapter 4",
    backdrop: "images/banner/john-wick-4.jpg",
    link: "/movie/12047",
    trailer: "https://youtu.be/cYX2_lDYZpI",
    tagline: "No way back. One way out.",
  },
  {
    id: 3,
    name: "Shazam! Fury of the Gods",
    backdrop: "images/banner/shazam.jpg",
    link: "/movie/12015",
    trailer: "https://youtu.be/S3L32B4T5Mo",
    tagline: "Oh. My. Gods.",
  },
  {
    id: 4,
    name: "Creed III",
    backdrop: "images/banner/creed.jpg",
    link: "/movie/12048",
    trailer: "https://youtu.be/AHmCH7iB_IM",
    tagline: "You can't run from your past.",
  },
  {
    id: 5,
    name: "Soulmate",
    backdrop: "images/banner/soulmate.jpg",
    link: "/movie/12050",
    trailer: "https://youtu.be/_lvG8xeHu40",
    tagline: "",
  },
];
